# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
  # param_fetcher_listener: true
  # allowed_methods_listener: true
  body_listener: true
  routing_loader: true
  view:
    view_response_listener: force
    formats:
      json: true
      jsonp: true
    mime_types:
      json:
        [
          'application/json',
          'application/x-json',
          'application/vnd.example-com.foo+json',
        ]
  # exception:
  # enabled: true
  # exception_controller: FOS\RestBundle\Controller\ExceptionController
  #        codes:
  #            App\Exception\MyException: 403
  #        messages:
  #            App\Exception\MyException: Forbidden area.
  format_listener:
    rules:
      - {
          path: ^/api,
          prefer_extension: false,
          fallback_format: json,
          priorities: [json],
        }
