version: '3.2'

services:
    db:
        image: mariadb:10.3
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD=true
        volumes:
            - db:/var/lib/mysql
    php:
        build:
            context: ./docker/php
        working_dir: /srv
        volumes:
            - ./:/srv/            
    http:
        image: nginx:1-alpine
        depends_on:
            - php
        volumes:
            - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf:ro
            - ./public/:/srv/public/:ro
    node:
        build:
            context: ./docker/node
        working_dir: /srv
        volumes:
            - ./:/srv/
volumes:
    db: ~