App\Domain\Model\Product:
  type: mappedSuperclass
  indexes:
    name_index:
      columns: [ name ]
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
      length: 50
    price:
      type: decimal
      unique: false
      precision: 6
      scale: 2
      options:
        default: 0.0
        comment: "Price in Euro"
    description:
      type: text
      nullable: true
