App\Store\Entity\ProductEntity:
  type: entity
  repositoryClass: App\Store\Repository\ProductRepository
  table: product
  schema: schema_name # The schema the table lies in, for platforms that support schemas (Optional, >= 2.5)
  readOnly: false
  indexes:
    name_index:
      columns: [ name ]
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
      column: name
      length: 50
    price:
      column: price
      type: decimal
      unique: false
      precision: 6
      scale: 2
      options:
        default: 0.0
        comment: "Price in Euro"
    description:
      column: description
      type: text
      nullable: true
    slug:
      column: slug
      type: string
      length: 255